appId: fr.cerema.scoutia
appName: SCOUT IA
webDir: app
plugins:
  Preferences:
    group: ScoutIAConfig
  CapacitorHttp:
    enabled: true
android:
  allowMixedContent: false
  captureInput: true
  webContentsDebuggingEnabled: false
